# -*- coding: utf-8 -*-
# Author: Tyrone
# Copyright (c) 2026
# -------------*-*-*--*-*-*--*-*-*------------


import os

# Configuration (run from repo root: python buildUI.py)
COMPONENTS_DIR = "frontend/components"
OUTPUT_FILE = "app/static/js/ui.js"
CORE_FILENAME = "core.js"

def get_source_files():
    """
    Scans the directory for JS files, ensuring core.js is first
    and the output file is ignored.
    """
    if not os.path.exists(COMPONENTS_DIR):
        print(f"[!] Error: Directory '{COMPONENTS_DIR}' does not exist.")
        return []

    core_file = []
    other_files = []
    output_abspath = os.path.abspath(OUTPUT_FILE)

    for filename in os.listdir(COMPONENTS_DIR):
        if filename.endswith('.js'):
            filepath = os.path.join(COMPONENTS_DIR, filename)

            # Never merge the bundle filename (legacy copies lived here before output → app/static/js)
            if filename == os.path.basename(OUTPUT_FILE):
                continue

            # CRITICAL: Prevent the script from reading its own output file (same dir edge case)
            if os.path.abspath(filepath) == output_abspath:
                continue
                
            if filename == CORE_FILENAME:
                core_file.append(filepath)
            else:
                other_files.append(filepath)

    # Sort other files alphabetically to ensure consistent builds across different machines
    other_files.sort()
    
    if not core_file:
        print(f"[!] Warning: '{CORE_FILENAME}' not found. UI Engine might fail to initialize.")
        
    return core_file + other_files

def build_ui():
    print(f"Scanning directory: {COMPONENTS_DIR}...")
    source_files = get_source_files()
    
    if not source_files:
        print("[!] No component files found to merge.")
        return

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    total_merged = 0

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as outfile:
        outfile.write("/* =============================================================\n")
        outfile.write("   UI LITE - AUTO-GENERATED COMPONENT FILE\n")
        outfile.write("   DO NOT EDIT THIS FILE DIRECTLY. EDIT THE SOURCE FILES INSTEAD.\n")
        outfile.write("   ============================================================= */\n\n")

        for file_path in source_files:
            with open(file_path, 'r', encoding='utf-8') as infile:
                filename = os.path.basename(file_path)
                outfile.write(f"/* -------------------------------------------------------------\n")
                outfile.write(f"   {os.path.splitext(filename)[0].capitalize()}\n")
                outfile.write(f"   ------------------------------------------------------------- */\n")
                outfile.write(infile.read() + "\n\n")
                
            print(f"[+] Merged successfully: {file_path}")
            total_merged += 1

    print(f"\nBuild complete! Successfully merged {total_merged} files.")
    print(f"Output saved to: {OUTPUT_FILE}")

if __name__ == '__main__':
    build_ui()