/* =============================================================
   UI LITE - AUTO-GENERATED COMPONENT FILE
   DO NOT EDIT THIS FILE DIRECTLY. EDIT THE SOURCE FILES INSTEAD.
   ============================================================= */

/* -------------------------------------------------------------
   Core
   ------------------------------------------------------------- */
window.UI = window.UI || {};

window.UI.init = function(context = document) {
    $(context).find('[data-ui]').each(function() {
        const $el = $(this);
        const componentName = $el.data('ui');
        
        if (window.UI[componentName] && !$el.data('nuxt-ui-instance')) {
            const instance = new window.UI[componentName](this);
            $el.data('nuxt-ui-instance', instance);
        }
    });
};

$(document).ready(() => {
    window.UI.init();
});

/* -------------------------------------------------------------
   Accordion
   ------------------------------------------------------------- */
class Accordion {
    constructor(element) {
        this.$el = $(element);
        // Add data-multiple="true" to HTML if you want multiple panels open at once
        this.allowMultiple = this.$el.data('multiple') === true; 
        this.init();
    }

    init() {
        this.$el.on('click', '.accordion-header', (e) => {
            const $header = $(e.currentTarget);
            const $item = $header.closest('.accordion-item');
            const $content = $item.find('.accordion-content');
            const $icon = $header.find('.accordion-icon');
            
            const isOpen = $item.hasClass('is-open');

            // If not allowing multiple, close all others
            if (!this.allowMultiple && !isOpen) {
                const $otherItems = this.$el.find('.accordion-item.is-open');
                $otherItems.removeClass('is-open');
                $otherItems.find('.accordion-content').slideUp(200);
                $otherItems.find('.accordion-icon').removeClass('rotate-180');
            }

            // Toggle current
            if (isOpen) {
                $item.removeClass('is-open');
                $content.slideUp(200);
                $icon.removeClass('rotate-180');
            } else {
                $item.addClass('is-open');
                $content.slideDown(200);
                $icon.addClass('rotate-180');
            }
        });

        // Initialize state based on HTML classes
        this.$el.find('.accordion-item').each((_, item) => {
            if (!$(item).hasClass('is-open')) {
                $(item).find('.accordion-content').hide();
            } else {
                $(item).find('.accordion-icon').addClass('rotate-180');
            }
        });
    }
}

window.UI.accordion = Accordion;

/* -------------------------------------------------------------
   Avatar
   ------------------------------------------------------------- */
class Avatar {
    constructor(element) {
        this.$el = $(element);
        this.$img = this.$el.find('img');
        this.$fallback = this.$el.find('.avatar-fallback');
        this.init();
    }

    init() {
        if (this.$img.length) {
            this.$img.on('error', () => {
                this.showFallback();
            });

            if (this.$img[0].complete && this.$img[0].naturalHeight === 0) {
                this.showFallback();
            }
        }
    }

    showFallback() {
        this.$img.addClass('hidden');
        
        if (this.$fallback.length) {
            this.$fallback.removeClass('hidden').addClass('flex items-center justify-center');
        } else {
            const defaultIcon = `
                <svg class="w-full h-full text-gray-400 bg-gray-100 p-1 rounded-full" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z" />
                </svg>
            `;
            this.$el.html(defaultIcon);
        }
    }
}

window.UI.avatar = Avatar;

/* -------------------------------------------------------------
   Badge
   ------------------------------------------------------------- */
class Badge {
    constructor(element) {
        this.$el = $(element);
        this.$dismissBtn = this.$el.find('[data-dismiss="badge"]');
        this.init();
    }

    init() {
        if (this.$dismissBtn.length) {
            this.$dismissBtn.on('click', (e) => {
                e.preventDefault();
                e.stopPropagation();
                this.dismiss();
            });
        }
    }

    dismiss() {
        this.$el.fadeOut(200, () => {
            this.$el.remove();
        });
    }
}

window.UI.badge = Badge;

/* -------------------------------------------------------------
   Breadcrumbs
   ------------------------------------------------------------- */
class Breadcrumbs {
    constructor(element) {
        this.$el = $(element);
    }

    /**
     * Re-renders the breadcrumb trail
     * @param {Array} items - Array of objects: [{ label: 'Home', url: '/' }, { label: 'Settings' }]
     */
    setItems(items) {
        if (!Array.isArray(items) || items.length === 0) {
            this.$el.empty();
            return;
        }

        let html = '<ol class="flex items-center space-x-2 text-sm text-gray-500">';
        
        const separator = `
            <svg class="h-4 w-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
            </svg>
        `;

        items.forEach((item, index) => {
            const isLast = index === items.length - 1;
            
            html += `<li><div class="flex items-center">`;
            
            if (index > 0) {
                html += separator;
            }

            if (isLast || !item.url) {
                // Active/Last item (No link)
                html += `<span class="ml-2 font-medium text-gray-900">${item.label}</span>`;
            } else {
                // Clickable link
                html += `<a href="${item.url}" class="${index > 0 ? 'ml-2 ' : ''}hover:text-gray-900 transition-colors">${item.label}</a>`;
            }
            
            html += `</div></li>`;
        });

        html += '</ol>';
        this.$el.html(html);
    }
}

window.UI.breadcrumbs = Breadcrumbs;

/* -------------------------------------------------------------
   Button
   ------------------------------------------------------------- */
class Button {
    constructor(element) {
        this.$el = $(element);
        this.originalContent = this.$el.html();
        this.isLoading = false;
    }

    /**
     * Set the button to a loading state, disabling it and showing a spinner.
     * @param {boolean} state 
     */
    setLoading(state) {
        this.isLoading = state;
        
        if (state) {
            this.$el.prop('disabled', true).addClass('opacity-75 cursor-not-allowed');
            
            const spinner = `
                <svg class="animate-spin -ml-1 mr-2 h-4 w-4 text-current inline-block" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
            `;
            
            this.$el.html(`<div class="flex items-center justify-center">${spinner} <span>${this.originalContent}</span></div>`);
        } else {
            this.$el.prop('disabled', false).removeClass('opacity-75 cursor-not-allowed');
            this.$el.html(this.originalContent);
        }
    }
}

window.UI.button = Button;

/* -------------------------------------------------------------
   Card
   ------------------------------------------------------------- */
class Card {
    constructor(element) {
        this.$el = $(element);
        this.$header = this.$el.find('.card-header');
        this.$body = this.$el.find('.card-body');
        this.$toggleIcon = this.$el.find('.card-toggle-icon');
        
        this.isCollapsed = this.$el.hasClass('is-collapsed');
        this.init();
    }

    init() {
        // Ensure card has relative positioning for the loading overlay
        if (!this.$el.hasClass('relative')) {
            this.$el.addClass('relative');
        }

        // Setup collapsible logic if header is clickable
        if (this.$header.hasClass('cursor-pointer')) {
            this.$header.on('click', () => this.toggle());
        }

        // Initial state
        if (this.isCollapsed) {
            this.$body.hide();
            this.$toggleIcon.addClass('rotate-180');
        }
    }

    toggle() {
        this.isCollapsed = !this.isCollapsed;
        if (this.isCollapsed) {
            this.$body.slideUp(200);
            this.$toggleIcon.addClass('rotate-180');
        } else {
            this.$body.slideDown(200);
            this.$toggleIcon.removeClass('rotate-180');
        }
    }

    /**
     * Shows or hides a loading overlay over the entire card
     * @param {boolean} isLoading 
     */
    setLoading(isLoading) {
        let $overlay = this.$el.find('.card-overlay');
        
        if (isLoading) {
            if ($overlay.length === 0) {
                const html = `
                    <div class="card-overlay absolute inset-0 bg-white/60 backdrop-blur-[1px] z-10 flex items-center justify-center rounded-lg">
                        <svg class="animate-spin h-8 w-8 text-blue-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                    </div>`;
                this.$el.append(html);
            } else {
                $overlay.removeClass('hidden');
            }
        } else {
            if ($overlay.length) {
                $overlay.addClass('hidden');
            }
        }
    }
}

window.UI.card = Card;

/* -------------------------------------------------------------
   Carousel
   ------------------------------------------------------------- */
class Carousel {
    constructor(element) {
        this.$el = $(element);
        this.$track = this.$el.find('.carousel-track');
        this.$btnNext = this.$el.find('.carousel-next');
        this.$btnPrev = this.$el.find('.carousel-prev');
        
        // Parse scroll amount from data attribute
        this.scrollAmount = parseInt(this.$el.data('scroll-amount')) || 300; 
        this.init();
    }

    init() {
        this.$btnNext.on('click', (e) => {
            e.preventDefault();
            this.scroll(this.scrollAmount, 'next');
        });

        this.$btnPrev.on('click', (e) => {
            e.preventDefault();
            this.scroll(-this.scrollAmount, 'prev');
        });
    }

    scroll(amount, direction) {
        const el = this.$track[0];
        const maxScrollLeft = el.scrollWidth - el.clientWidth;
        const currentScroll = this.$track.scrollLeft();
        
        let targetScroll = currentScroll + amount;

        // Tolerance of 5px for floating point rendering issues
        if (direction === 'next' && currentScroll >= maxScrollLeft - 5) {
            // Reached the end, rewind to start
            targetScroll = 0; 
        } else if (direction === 'prev' && currentScroll <= 5) {
            // Reached the start, fast-forward to end
            targetScroll = maxScrollLeft; 
        }

        // Animate smoothly
        this.$track.animate({
            scrollLeft: targetScroll
        }, 400);
    }
}

window.UI.carousel = Carousel;

/* -------------------------------------------------------------
   Datepicker
   ------------------------------------------------------------- */
class DatePicker {
    constructor(element) {
        this.$el = $(element);
        this.$input = this.$el.find('input[type="date"]');
        this.init();
    }

    init() {
        // Automatically open the native date picker when clicking anywhere on the wrapper
        this.$el.on('click', () => {
            try {
                this.$input[0].showPicker(); // Supported in modern browsers
            } catch (e) {
                this.$input.focus(); // Fallback for older browsers
            }
        });

        // Add CSS to hide native calendar icon via JS if not done in CSS
        if (!$('#ui-datepicker-styles').length) {
            $('head').append(`
                <style id="ui-datepicker-styles">
                    /* Hide native calendar icon in webkit */
                    input[type="date"]::-webkit-calendar-picker-indicator {
                        background: transparent;
                        bottom: 0;
                        color: transparent;
                        cursor: pointer;
                        height: auto;
                        left: 0;
                        position: absolute;
                        right: 0;
                        top: 0;
                        width: auto;
                    }
                </style>
            `);
        }
    }

    /**
     * Get the date value in YYYY-MM-DD format suitable for backend API
     * @returns {string}
     */
    getValue() {
        return this.$input.val();
    }

    /**
     * Set the date value
     * @param {string} dateString - Format YYYY-MM-DD
     */
    setValue(dateString) {
        this.$input.val(dateString);
    }
    
    /**
     * Show validation error styling
     */
    setError(message) {
        this.$el.removeClass('border-gray-300').addClass('border-red-500 ring-1 ring-red-500');
        // Optional: you could append an error message element here similarly to input.js
    }
}

window.UI.datepicker = DatePicker;

/* -------------------------------------------------------------
   Input
   ------------------------------------------------------------- */
class Input {
    constructor(element) {
        this.$el = $(element);
        this.$input = this.$el.find('input, textarea');
        this.$errorText = this.$el.find('.error-message');
        this.init();
    }

    init() {
        // Clear error styling dynamically when user starts typing again
        this.$input.on('input', () => {
            if (this.$input.hasClass('border-red-500')) {
                this.clearError();
            }
        });
    }

    /**
     * Display error state based on API response
     * @param {string} message - Validation error message from server
     */
    setError(message) {
        // Update input borders
        this.$input
            .removeClass('border-gray-300 focus:ring-blue-500 focus:border-blue-500')
            .addClass('border-red-500 focus:ring-red-500 focus:border-red-500');
            
        // Render or update error message text
        if (this.$errorText.length) {
            this.$errorText.text(message).removeClass('hidden');
        } else {
            this.$el.append(`<p class="error-message text-sm text-red-500 mt-1">${message}</p>`);
            this.$errorText = this.$el.find('.error-message');
        }
    }

    clearError() {
        this.$input
            .removeClass('border-red-500 focus:ring-red-500 focus:border-red-500')
            .addClass('border-gray-300 focus:ring-blue-500 focus:border-blue-500');
            
        if (this.$errorText.length) {
            this.$errorText.addClass('hidden');
        }
    }
}

window.UI.input = Input;

/* -------------------------------------------------------------
   Modal
   ------------------------------------------------------------- */
class Modal {
    constructor(element) {
        this.$el = $(element);
        this.$backdrop = this.$el.find('.modal-backdrop');
        this.$panel = this.$el.find('.modal-panel');
        this.$closeBtns = this.$el.find('[data-dismiss="modal"]');
        
        this.isOpen = !this.$el.hasClass('hidden');
        this.init();
    }

    init() {
        // Trigger to open modal (find any button with data-target="#this-modal-id")
        const modalId = this.$el.attr('id');
        if (modalId) {
            $(document).on('click', `[data-target="#${modalId}"]`, (e) => {
                e.preventDefault();
                this.open();
            });
        }

        // Close on button click
        this.$closeBtns.on('click', (e) => {
            e.preventDefault();
            this.close();
        });

        // Close on backdrop click
        this.$backdrop.on('click', () => {
            this.close();
        });

        // Close on ESC key press
        $(document).on('keydown', (e) => {
            if (e.key === 'Escape' && this.isOpen) {
                this.close();
            }
        });
    }

    open() {
        if (this.isOpen) return;
        
        // Lock body scroll
        $('body').addClass('overflow-hidden');
        
        // Show modal wrapper
        this.$el.removeClass('hidden');
        
        // Animate in
        setTimeout(() => {
            this.$backdrop.removeClass('opacity-0').addClass('opacity-100');
            this.$panel.removeClass('opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95')
                       .addClass('opacity-100 translate-y-0 sm:scale-100');
        }, 10); // Small delay to allow display:block to apply before animating

        this.isOpen = true;
    }

    close() {
        if (!this.isOpen) return;

        // Animate out
        this.$backdrop.removeClass('opacity-100').addClass('opacity-0');
        this.$panel.removeClass('opacity-100 translate-y-0 sm:scale-100')
                   .addClass('opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95');

        // Hide wrapper and unlock body after animation ends (300ms matches Tailwind duration-300)
        setTimeout(() => {
            this.$el.addClass('hidden');
            $('body').removeClass('overflow-hidden');
        }, 300);

        this.isOpen = false;
    }
}

window.UI.modal = Modal;

/* -------------------------------------------------------------
   Pagination
   ------------------------------------------------------------- */
class Pagination {
    constructor(element) {
        this.$el = $(element);
        this.init();
    }

    init() {
        this.$el.on('click', '[data-page]', (e) => {
            e.preventDefault();
            const page = $(e.currentTarget).data('page');
            
            if (page === 'prev' || page === 'next') {
                // Logic for prev/next buttons should be handled in your API service
                this.triggerChange(page);
            } else {
                this.setCurrentPage(parseInt(page));
                this.triggerChange(page);
            }
        });
    }

    setCurrentPage(pageNumber) {
        this.$el.find('[data-page]').removeClass('z-10 bg-blue-600 text-white')
                 .addClass('text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50');
        
        this.$el.find(`[data-page="${pageNumber}"]`)
                 .removeClass('text-gray-900 ring-gray-300')
                 .addClass('z-10 bg-blue-600 text-white');
    }

    triggerChange(page) {
        // Custom event so you can listen to it in your page.js
        this.$el.trigger('ui:page-change', { page: page });
    }
}

window.UI.pagination = Pagination;

/* -------------------------------------------------------------
   Popover
   ------------------------------------------------------------- */
class Popover {
    constructor(element) {
        this.$el = $(element);
        this.$trigger = this.$el.find('.popover-trigger');
        this.$panel = this.$el.find('.popover-panel');
        this.isOpen = false;
        this.init();
    }

    init() {
        this.$trigger.on('click', (e) => {
            e.preventDefault();
            e.stopPropagation();
            this.toggle();
        });

        // Close on outside click
        $(document).on('click', (e) => {
            if (this.isOpen && !this.$el.is(e.target) && this.$el.has(e.target).length === 0) {
                this.close();
            }
        });
        
        // Prevent clicking inside panel from closing it
        this.$panel.on('click', (e) => {
            e.stopPropagation();
        });
    }

    toggle() {
        this.isOpen ? this.close() : this.open();
    }

    open() {
        // Tailwind transition classes
        this.$panel.removeClass('hidden opacity-0 scale-95').addClass('opacity-100 scale-100');
        this.isOpen = true;
    }

    close() {
        this.$panel.removeClass('opacity-100 scale-100').addClass('opacity-0 scale-95');
        // Hide completely after fade out animation (duration-150)
        setTimeout(() => {
            if (!this.isOpen) this.$panel.addClass('hidden');
        }, 150);
        this.isOpen = false;
    }
}

window.UI.popover = Popover;

/* -------------------------------------------------------------
   Progress
   ------------------------------------------------------------- */
class Progress {
    constructor(element) {
        this.$el = $(element);
        this.$bar = this.$el.find('.progress-bar');
        this.$text = this.$el.find('.progress-text'); // Optional text indicator
        this.init();
    }

    init() {
        // Read initial value from data attribute if exists
        const initialValue = this.$el.data('value') || 0;
        this.setValue(initialValue);
    }

    /**
     * Updates the progress bar width
     * @param {number} percent - Value from 0 to 100
     */
    setValue(percent) {
        // Clamp value between 0 and 100
        const clampedValue = Math.max(0, Math.min(100, percent));
        
        // Update UI
        this.$bar.css('width', `${clampedValue}%`);
        this.$el.data('value', clampedValue);
        
        if (this.$text.length) {
            this.$text.text(`${Math.round(clampedValue)}%`);
        }
    }
}

window.UI.progress = Progress;

/* -------------------------------------------------------------
   Select
   ------------------------------------------------------------- */
class Select {
    constructor(element) {
        this.$el = $(element);
        this.$hiddenInput = this.$el.find('input[type="hidden"]');
        this.$trigger = this.$el.find('.select-trigger');
        this.$triggerText = this.$el.find('.select-text');
        this.$menu = this.$el.find('.select-menu');
        this.$options = this.$el.find('.select-option');
        
        this.isOpen = false;
        this.init();
    }

    init() {
        // Toggle menu
        this.$trigger.on('click', (e) => {
            e.preventDefault();
            this.toggle();
        });

        // Select an option
        this.$options.on('click', (e) => {
            const $selected = $(e.currentTarget);
            const val = $selected.data('value');
            const text = $selected.text();

            // Update UI & Hidden Input
            this.$triggerText.text(text).removeClass('text-gray-400').addClass('text-gray-900');
            this.$hiddenInput.val(val).trigger('change');
            
            // Handle active styling
            this.$options.removeClass('bg-blue-50 text-blue-600 font-medium');
            $selected.addClass('bg-blue-50 text-blue-600 font-medium');

            this.close();
        });

        // Close when clicking outside
        $(document).on('click', (e) => {
            if (this.isOpen && !this.$el.is(e.target) && this.$el.has(e.target).length === 0) {
                this.close();
            }
        });
    }

    toggle() {
        this.isOpen ? this.close() : this.open();
    }

    open() {
        this.$menu.removeClass('hidden').hide().fadeIn(150);
        this.$trigger.addClass('border-blue-500 ring-1 ring-blue-500');
        this.isOpen = true;
    }

    close() {
        this.$menu.fadeOut(100, () => this.$menu.addClass('hidden').css('display', ''));
        this.$trigger.removeClass('border-blue-500 ring-1 ring-blue-500');
        this.isOpen = false;
    }
}

window.UI.select = Select;

/* -------------------------------------------------------------
   Skeleton
   ------------------------------------------------------------- */
class Skeleton {
    constructor(element) {
        this.$el = $(element);
        this.$content = this.$el.find('.skeleton-content');
        this.$placeholders = this.$el.find('.skeleton-placeholder');
    }

    /**
     * Toggle loading state
     * @param {boolean} isLoading 
     */
    setLoading(isLoading) {
        if (isLoading) {
            this.$content.addClass('hidden');
            this.$placeholders.removeClass('hidden');
        } else {
            this.$placeholders.addClass('hidden');
            this.$content.removeClass('hidden');
        }
    }
}

window.UI.skeleton = Skeleton;

/* -------------------------------------------------------------
   Table
   ------------------------------------------------------------- */
class Table {
    constructor(element) {
        this.$el = $(element);
        this.$selectAll = this.$el.find('.select-all-checkbox');
        this.$sortHeaders = this.$el.find('th[data-sortable]');
        this.init();
    }

    init() {
        // Handle Select All checkbox
        this.$selectAll.on('change', (e) => {
            const isChecked = $(e.currentTarget).prop('checked');
            // Find all row checkboxes dynamically (useful if rows are injected later via CSR)
            const $rowCheckboxes = this.$el.find('.row-checkbox');
            $rowCheckboxes.prop('checked', isChecked);
            this.updateRowStyles();
        });

        // Handle individual row checkbox (Delegate event for dynamically added rows)
        this.$el.on('change', '.row-checkbox', () => {
            const $rowCheckboxes = this.$el.find('.row-checkbox');
            const total = $rowCheckboxes.length;
            const checked = $rowCheckboxes.filter(':checked').length;
            
            this.$selectAll.prop('checked', total > 0 && total === checked);
            this.updateRowStyles();
        });

        // Handle Sortable Headers
        this.$sortHeaders.on('click', (e) => {
            const $header = $(e.currentTarget);
            const column = $header.data('sortable');
            const currentDirection = $header.data('direction') || 'none';
            
            // Determine next direction (none -> asc -> desc -> asc)
            let nextDirection = currentDirection === 'asc' ? 'desc' : 'asc';
            
            // Reset UI for all headers
            this.$sortHeaders.data('direction', 'none');
            this.$sortHeaders.find('.sort-icon')
                .removeClass('text-blue-600 rotate-180')
                .addClass('text-gray-400 opacity-0 group-hover:opacity-100');

            // Apply UI to clicked header
            $header.data('direction', nextDirection);
            const $icon = $header.find('.sort-icon');
            $icon.removeClass('text-gray-400 opacity-0 group-hover:opacity-100').addClass('text-blue-600 opacity-100');
            if (nextDirection === 'desc') $icon.addClass('rotate-180');

            // Trigger custom event so page script can fetch new data from Flask
            this.$el.trigger('ui:sort', { column: column, direction: nextDirection });
        });
    }

    updateRowStyles() {
        this.$el.find('.row-checkbox').each((idx, el) => {
            const $row = $(el).closest('tr');
            if ($(el).prop('checked')) {
                $row.addClass('bg-blue-50');
            } else {
                $row.removeClass('bg-blue-50');
            }
        });
    }

    /**
     * Utility method for API calls
     * @returns {Array} List of selected row values (e.g., IDs)
     */
    getSelectedValues() {
        return this.$el.find('.row-checkbox:checked').map(function() {
            return $(this).val();
        }).get();
    }
}

window.UI.table = Table;

/* -------------------------------------------------------------
   Tabs
   ------------------------------------------------------------- */
class Tabs {
    constructor(element) {
        this.$el = $(element);
        this.$buttons = this.$el.find('[data-tab-target]');
        this.init();
    }

    init() {
        this.$buttons.on('click', (e) => {
            e.preventDefault();
            const $clickedTab = $(e.currentTarget);
            const targetId = $clickedTab.data('tab-target');
            
            this.activate(targetId, $clickedTab);
        });
    }

    /**
     * Activate a specific tab and its panel
     * @param {string} targetId - ID of the panel to show
     * @param {jQuery} $tabBtn - The jQuery object of the clicked tab
     */
    activate(targetId, $tabBtn) {
        // 1. Update Tab Buttons UI
        this.$buttons.removeClass('border-blue-500 text-blue-600')
                     .addClass('border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300');
        
        $tabBtn.removeClass('border-transparent text-gray-500')
               .addClass('border-blue-500 text-blue-600');

        // 2. Update Panels
        const $targetPanel = $(targetId);
        if ($targetPanel.length) {
            // Hide all sibling panels
            $targetPanel.parent().children().addClass('hidden');
            // Show target panel
            $targetPanel.removeClass('hidden');
        }
    }
}

window.UI.tabs = Tabs;

/* -------------------------------------------------------------
   Toast
   ------------------------------------------------------------- */
class ToastManager {
    constructor() {
        this.containerId = 'ui-toast-container';
        this.initContainer();
    }

    initContainer() {
        if ($(`#${this.containerId}`).length === 0) {
            $('body').append(`
                <div id="${this.containerId}" aria-live="assertive" class="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6 z-[100]">
                    <div class="flex w-full flex-col items-center space-y-4 sm:items-end"></div>
                </div>
            `);
        }
        this.$container = $(`#${this.containerId} > div`);
    }

    /**
     * Show a notification toast
     * @param {string} title - Main message
     * @param {string} description - Subtext (optional)
     * @param {string} type - 'success', 'error', 'warning', 'info'
     * @param {number} duration - Time in ms before auto-close
     */
    show(title, description = '', type = 'success', duration = 3000) {
        // Define icons and colors based on type
        const styles = {
            success: { icon: '<path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />', color: 'text-green-400' },
            error: { icon: '<path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />', color: 'text-red-400' },
            info: { icon: '<path stroke-linecap="round" stroke-linejoin="round" d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z" />', color: 'text-blue-400' }
        };

        const currentStyle = styles[type] || styles.info;
        const toastId = 'toast-' + Math.random().toString(36).substr(2, 9);

        const html = `
            <div id="${toastId}" class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5 transition transform translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2">
                <div class="p-4">
                    <div class="flex items-start">
                        <div class="flex-shrink-0">
                            <svg class="h-6 w-6 ${currentStyle.color}" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                ${currentStyle.icon}
                            </svg>
                        </div>
                        <div class="ml-3 w-0 flex-1 pt-0.5">
                            <p class="text-sm font-medium text-gray-900">${title}</p>
                            ${description ? `<p class="mt-1 text-sm text-gray-500">${description}</p>` : ''}
                        </div>
                        <div class="ml-4 flex flex-shrink-0">
                            <button type="button" class="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none" onclick="$('#${toastId}').fadeOut(300, function(){ $(this).remove(); })">
                                <span class="sr-only">Close</span>
                                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                    <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        `;

        const $toast = $(html);
        this.$container.append($toast);

        // Animate in (Slide from right/bottom)
        setTimeout(() => {
            $toast.removeClass('translate-y-2 opacity-0 sm:translate-x-2').addClass('translate-y-0 opacity-100 sm:translate-x-0');
        }, 10);

        // Auto remove
        if (duration > 0) {
            setTimeout(() => {
                $toast.fadeOut(300, function() { $(this).remove(); });
            }, duration);
        }
    }
}

// Khởi tạo một instance duy nhất (Singleton) có thể gọi ở bất cứ đâu
window.UI.toast = new ToastManager();

/* -------------------------------------------------------------
   Toggle
   ------------------------------------------------------------- */
class Toggle {
    constructor(element) {
        this.$el = $(element);
        this.$input = this.$el.find('input[type="checkbox"]');
        this.$track = this.$el.find('.toggle-track');
        this.$thumb = this.$el.find('.toggle-thumb');
        this.init();
    }

    init() {
        // Handle click on the wrapper
        this.$el.on('click', (e) => {
            if (this.$input.prop('disabled')) return;
            
            // Prevent double-toggling if they actually clicked the hidden input
            if (e.target !== this.$input[0]) {
                this.$input.prop('checked', !this.$input.prop('checked')).trigger('change');
            }
            this.updateUI();
        });

        // Sync initial state from HTML
        this.updateUI();
    }

    updateUI() {
        const isChecked = this.$input.prop('checked');
        
        if (isChecked) {
            this.$track.removeClass('bg-gray-200').addClass('bg-blue-600');
            this.$thumb.addClass('translate-x-5'); // Move to right
        } else {
            this.$track.removeClass('bg-blue-600').addClass('bg-gray-200');
            this.$thumb.removeClass('translate-x-5'); // Move to left
        }
    }
}

window.UI.toggle = Toggle;

